# Generated by Django 3.1.2 on 2020-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=150)),
                ('section', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=100)),
                ('instructorfullname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('major', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
